In [2]:
! pip install geopy

Requirement already satisfied: geopy in c:\users\sanchari chowdhuri\anaconda2\lib\site-packages

In [1]:
import pandas as pd

In [2]:
#importing  combined dataframe

df1=pd.read_csv("DCPart1 WS.csv")
#df=df1.head(120)
loc_df=df1['user_location']
len(loc_df)
#loc_df[40:60]

825

In [3]:
import time

In [4]:
#geocoding data
from geopy.geocoders import Nominatim
geolocator = Nominatim()
appended_data = []
#d = geolocator.geocode()
for city in loc_df:
        loc = geolocator.geocode(city)
        appended_data.append(loc)
        print len(appended_data)
        time.sleep(1)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701

GeocoderTimedOut: Service timed out

In [5]:
len(appended_data)

701

In [6]:
#saving it in dataframe
G_df = pd.DataFrame({'Geocoded Location':appended_data})
G_df.head(10)

                                   Geocoded Location
0  (NYC, New York, United States of America, (40....
1  (Centralia, Lewis County, Washington, United S...
2                                               None
3  (Washington, District of Columbia, United Stat...
4  (Louisiana and Arkansas Rr Lake Dam, Hunt Coun...
5  (Paterson, Passaic County, New Jersey, United ...
6  (Texas, United States of America, (31.8160381,...
7  (Park Forest, Cook County, Illinois, United St...
8  (Baltimore, Maryland, United States of America...
9  (Concord, Cabarrus County, North Carolina, Uni...

In [18]:

commentsnew_df=G_df['Geocoded Location']

In [19]:
#saving dataframe in csv
G_df.to_csv("location.csv", index=False,encoding ='utf8')

In [3]:
#readig csv
df2=pd.read_csv("location.csv")

In [4]:
#converting entire dataframe in string
df2['Geocoded Location'].apply(str)

0      (NYC, New York, United States of America, (40....
1      (Centralia, Lewis County, Washington, United S...
2      (Washington, District of Columbia, United Stat...
3      (Louisiana and Arkansas Rr Lake Dam, Hunt Coun...
4      (Paterson, Passaic County, New Jersey, United ...
5      (Texas, United States of America, (31.8160381,...
6      (Park Forest, Cook County, Illinois, United St...
7      (Baltimore, Maryland, United States of America...
8      (Concord, Cabarrus County, North Carolina, Uni...
9      (Washington, District of Columbia, United Stat...
10     (Earth Sciences and Map Library, 50, Soule Roa...
11     (Arizona, United States of America, (34.395342...
12     (Vermont, United States of America, (44.599071...
13     (Houston, Harris County, Texas, United States ...
14     (Atlanta, Fulton County, Georgia, United State...
15     (Massachusetts, United States of America, (42....
16     (North Hollywood, LA, Los Angeles County, Cali...
17     (Greensboro Street, Fayetteville, Cumberland C...
18     (Detroit, Wayne County, Michigan, United State...
19     (Houston, Harris County, Texas, United States ...
20     (Dallas, Dallas County, Texas, United States o...
21     (Philadelphia, Philadelphia County, Pennsylvan...
22     (Phoenix, Maricopa County, Arizona, United Sta...
23     (Miami, Miami-Dade County, Florida, United Sta...
24     (LA, Los Angeles County, California, United St...
25     (Philadelphia, Philadelphia County, Pennsylvan...
26     (Georgia, United States of America, (32.329380...
27     (Washington, District of Columbia, United Stat...
28     (College Park, Prince George's County, Marylan...
29     (Norfolk, Norfolk County, Massachusetts, 02056...
                             ...
615    (Chicago, Cook County, Illinois, United States...
616    (Chicago, Cook County, Illinois, United States...
617    (Alaska, United States of America, (64.4459613...
618    (Jacksonville, Duval County, Florida, United S...
619    (NYC, New York, United States of America, (40....
620    (Aguadilla, Puerto Rico, United States of Amer...
621    (Washington, District of Columbia, United Stat...
622    (Somerset County, Pennsylvania, United States ...
623    (Scottsdale, Maricopa County, Arizona, United ...
624    (Oklahoma, United States of America, (34.95508...
625    (Charleston, Coles County, Illinois, United St...
626    (Oregon, United States of America, (43.9792797...
627    (Chicago, Cook County, Illinois, United States...
628    (Durham, Durham County, North Carolina, United...
629    (SC, Região Sul, Brasil, (-27.0628366, -51.114...
630    (Maryland, United States of America, (39.51622...
631    (NYC, New York, United States of America, (40....
632    (Virginia, United States of America, (37.12322...
633    (Michigan, United States of America, (43.62119...
634    (NYC, New York, United States of America, (40....
635                          (Norda poluso, (90.0, 0.0))
636    (LA, Los Angeles County, California, United St...
637    (Louisiana, United States of America, (30.8703...
638    (Washington, District of Columbia, United Stat...
639    (Charleston, Charleston County, South Carolina...
640    (New Jersey, United States of America, (40.075...
641    (DMV, 3201, Horseless Carriage Drive, Norco, R...
642    (Dallas, Dallas County, Texas, United States o...
643    (Atlanta, Fulton County, Georgia, United State...
644    (Usa, Friedberg, Wetteraukreis, Regierungsbezi...
Name: Geocoded Location, dtype: object

In [5]:
#string slicing based on first word
df2['Geocoded Location'] = df2['Geocoded Location'].astype(str)

#but it remove numbers 
df2['Geocoded Location'] = df2['Geocoded Location'].str.extract('([a-zA-Z ]+)', expand=False).str.strip()

In [10]:
df2.head(5)

                    Geocoded Location  state
0                                 NYC    NaN
1                           Centralia    NaN
2                          Washington    NaN
3  Louisiana and Arkansas Rr Lake Dam    NaN
4                            Paterson    NaN

In [11]:
#comparing geocoded and sctual location
df_col_merged =pd.concat([df1, df2], axis=1)
df_col_merged.head(2)

,id,text,created_at,retweet_count,favorite_count,source,user_id,user_screen_name,user_name,user_created_at,user_description,user_followers_count,user_friends_count,user_location,geo_enabled,time_zone,Geocoded Location,state
0,8.480000e+17,RT @Saisailu97: now how 'bout we start trying ...,04/02/17 2:19,7,0,Twitter for iPhone,1.051942e+09,SupTifff,Tiff 🥂,01/01/13 6:08,Cosmonaut ☕️,548,294,"New York, NY",True,Eastern Time (US & Canada),NYC,NaN
1,8.480000e+17,RT @AntonioArellano: The tragedy of DC's missi...,04/02/17 2:17,21,0,Twitter for Android,8.230000e+17,Buddhababy10,Buddhababy,01/20/17 20:07,Bernie independent #ExGOP in the red belt of W...,576,1141,"Centralia, WA",False,NaN,Centralia,NaN